# toml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
final_space = true

[palette]
blue = "#8AADF4"
blueish = "#8AEDFF   "
lavender = "#B7BDF8"
os = "#ACB0BE"
pink = "#F5BDE6"
text = "#494D64"
wight = "#FFFFFF"

[transient_prompt]
template = "{{ .Shell }}> "
foreground = "#ffffff"
background = "transparent"

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  template = "  {{ .Full }} "
  trailing_diamond = ""
  foreground = "#100e23"
  background = "#906cff"
  type = "python"
  style = "diamond"

    [blocks.segments.properties]
    cache_duration = "none"

  [[blocks.segments]]
  trailing_diamond = ""
  template = " {{ .HEAD }}"
  foreground = "p:text"
  background = "p:lavender"
  type = "git"
  style = "diamond"

    [blocks.segments.properties]
    branch_icon = " "
    cache_duration = "none"
    cherry_pick_icon = " "
    commit_icon = " "
    fetch_status = false
    fetch_upstream_icon = false
    merge_icon = " "
    no_commits_icon = " "
    rebase_icon = " "
    revert_icon = " "
    tag_icon = " "

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  template = " {{.Icon}} "
  foreground = "p:wight"
  background = "p:blue"
  type = "os"
  style = "diamond"

    [blocks.segments.properties]
    cache_duration = "none"

  [[blocks.segments]]
  template = "{{if .Env.MSYSTEM_PREFIX}}{{ .Env.MSYSTEM }}{{end}}"
  foreground = "p:text"
  background = "p:blueish"
  type = "text"
  powerline_symbol = ""
  style = "powerline"

    [blocks.segments.properties]
    cache_duration = "none"

  [[blocks.segments]]
  template = " {{ .Path }}"
  foreground = "p:text"
  background = "p:pink"
  powerline_symbol = ""
  type = "path"
  style = "powerline"

    [blocks.segments.properties]
    cache_duration = "none"
    folder_icon = "...."
    home_icon = "~"
    style = "agnoster_short"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  template = "➜"
  foreground = "#007ACC"
  type = "text"
  style = "plain"

    [blocks.segments.properties]
    cache_duration = "none"

